# configs/modules/data_pipeline.yaml

# Project root directory
project_root: "."

# ===========================
# DATA PIPELINE MODULE CONFIG
# ===========================
data_pipeline:
#REQUIRED_FIELDS = 
#{'data_pipeline_dir': str,
#'data_pipeline_change_log_path': str,
#'manual_review_notifications_dir': str,
#'shared_database_dir': str,
#'annotation_path': str}

  # --------------------------------------------
  # BASE DIRECTORIES (Required - it will be resolved with project_root)
  # --------------------------------------------
  db_dir: "tests/mock_database" 
  default_dir: 'tests/shared_db'

  # --------------------------------------------
  # OPTIONAL OVERRIDES
  # Uncomment to override default paths
  # --------------------------------------------

  # Path to database schemas
  # Default: {self.db_dir}/databaseSchemas.json
  # databaseSchemas_path: "tests/mock_database/databaseSchemas.json"
  
  # DataPipelineOrchestrator directory
  # Default: {default_dir}/DataPipelineOrchestrator
  # data_pipeline_dir: "tests/shared_db/DataPipelineOrchestrator"

  # DataPipelineOrchestrator change log
  # Default: {data_pipeline_dir}/change_log.txt
  # data_pipeline_change_log_path: "tests/shared_db/DataPipelineOrchestrator/change_log.txt"

  # Path to healing notifications directory
  # Default: {data_pipeline_dir}/notifications
  # manual_review_notifications_dir: "tests/shared_db/DataPipelineOrchestrator/notifications"

  # Path to shared database directory
  # Default: {data_pipeline_dir}/DataCollector
  # shared_database_dir: "tests/shared_db/DataPipelineOrchestrator/DataCollector"

  # Path to annotations
  # Default: {shared_database_dir}/newest/path_annotations.json
  # annotation_path: "tests/shared_db/DataPipelineOrchestrator/DataCollector/newest/path_annotations.json" 