# configs/modules/data_pipeline.yaml

# Project root directory
project_root: "."

# ===========================
# DATA PIPELINE MODULE CONFIG
# ===========================
data_pipeline:
  #REQUIRED_FIELDS = {'dynamic_db_dir': str, 'databaseSchemas_path': str, 'annotation_path': str, 'data_pipeline_dir': str}

  # Source data directory (dynamic database)
  db_dir: "tests/mock_database" 
  # => dynamic_db_dir = f"{self.db_dir}/dynamicDatabase"
  # => databaseSchemas_path = f"{self.db_dir}/databaseSchemas.json"

  default_dir: 'tests/shared_db'
  #data_pipeline_dir = f"{default_dir}/DataPipelineOrchestrator"
  #annotation_path = f"{data_pipeline_dir}/DataLoaderAgent/newest/path_annotations.json" 
  