# configs/modules/initial_planning.yaml

# Project root directory
project_root: "."

# ========================
# VALIDATION MODULE CONFIG
# ========================
initial_planning:
#REQUIRED_FIELDS = {
#        'config': {
#            'shared_source_config': {
#                'annotation_path': str,
#                'databaseSchemas_path': str,
#                'sharedDatabaseSchemas_path': str,
#                'progress_tracker_change_log_path': str,
#                'mold_machine_weights_hist_path': str,
#                'mold_stability_index_change_log_path': str,
#                'initial_planner_dir': str,
#                'initial_planner_change_log_path': str,
#                'initial_planner_constant_config_path': str, 
#                'producing_processor_dir': str,
#                'producing_processor_change_log_path': str
#                'pending_processor_dir': str,
#                'pending_processor_change_log_path': str,
#                'auto_planner_dir': str,
#                'auto_planner_change_log_path': str
#                },
#            'efficiency': float,
#            'loss': float,
#            'initial_planner': {
#                'enabled': bool,
#                'save_result': bool,
#                "priority_order": str,
#                'max_load_threshold': int,
#                'log_progress_interval': int
#                },
#            'save_planner_log': bool
#            }
#        }

  shared_source_config:
    # --------------------------------------------
    # BASE DIRECTORIES (Required - it will be resolved with project_root)
    # --------------------------------------------
    db_dir: "tests/mock_database" 
    default_dir: 'tests/shared_db'

    # --------------------------------------------
    # OPTIONAL OVERRIDES
    # Uncomment to override default paths
    # --------------------------------------------
    
    # Annotation path  
    # Default: {default_dir}/DataPipelineOrchestrator/DataLoaderAgent/newest/path_annotations.json
    # annotation_path: "tests/shared_db/DataPipelineOrchestrator/DataLoaderAgent/newest/path_annotations.json"

    # Database schemas path
    # Default: {db_dir}/databaseSchemas.json
    # databaseSchemas_path: "tests/mock_database/databaseSchemas.json"

    # Shared database schemas path
    # Default: {self.db_dir}/sharedDatabaseSchemas.json
    # sharedDatabaseSchemas_path = "tests/mock_database/sharedDatabaseSchemas.json"

    # Progress tracker change log
    # Default: {progress_tracker_dir}/change_log.txt
    # progress_tracker_change_log_path: "tests/shared_db/OrderProgressTracker/change_log.txt"

    # Mold machine weights hist path: 
    # Default: {self.features_extractor_dir}/MoldMachineFeatureWeightCalculator/weights_hist.xlsx
    # mold_machine_weights_hist_path: "tests/shared_db/AutoPlanner/HistoricalFeaturesExtractor/MoldMachineFeatureWeightCalculator/weights_hist.xlsx"

    # Mold stability index calculator change log
    # Default: {self.features_extractor_dir}/MoldStabilityIndexCalculator/change_log.txt
    # mold_stability_index_change_log_path: "tests/shared_db/AutoPlanner/HistoricalFeaturesExtractor/MoldStabilityIndexCalculator/change_log.txt"

    # Auto planner directory
    # Default: {self.default_dir}/AutoPlanner
    # auto_planner_dir: "tests/shared_db/AutoPlanner"

    # Auto planner change log
    # Default: {self.auto_planner_dir}/change_log.txt
    # auto_planner_change_log_path: "tests/shared_db/AutoPlanner/change_log.txt"
    
    # Initial planner directory
    # Default: {self.auto_planner_dir}/InitialPlanner
    # initial_planner_dir: "tests/shared_db/AutoPlanner/InitialPlanner"

    # Initial planner change log
    # Default: {self.initial_planner_dir}/change_log.txt
    # initial_planner_change_log_path: "tests/shared_db/AutoPlanner/InitialPlanner/change_log.txt"

    # Initial planner constant config
    # Default: agents/autoPlanner/phases/initialPlanner/configs/constant_configurations.json
    # initial_planner_constant_config_path: "agents/autoPlanner/phases/initialPlanner/configs/constant_configurations.json"

    # Producing orders planner directory
    # Default: {self.initial_planner_dir}r/ProducingProcessor
    # producing_processor_dir: "tests/shared_db/AutoPlanner/InitialPlanner/ProducingProcessor"

    # Producing orders planner change log
    # Default: {self.producing_processor_dir}/change_log.txt
    # producing_processor_change_log_path: "tests/shared_db/AutoPlanner/InitialPlanner/ProducingProcessor/change_log.txt"

    # Pending orders planner directory
    # Default: {self.initial_planner_dir}/PendingProcessor
    # pending_processor_dir: "tests/shared_db/AutoPlanner/InitialPlanner/PendingProcessor"

    # Pending orders planner change log
    # Default: {self.pending_processor_dir}/change_log.txt
    # pending_processor_change_log_path: "tests/shared_db/AutoPlanner/InitialPlanner/PendingProcessor/change_log.txt"

  efficiency: 0.85
  loss: 0.03

  initial_planner:
    enabled: true
    save_result: true

    # Priority ordering strategy
    # Default: priority_order_1
    # priority_order: "priority_order_1"
    
    # Maximum allowed load threshold. If None, no load constraint is applied
    # Default: 30
    # max_load_threshold: 30

    # Interval at which progress logs are emitted during processing
    # Default: 10
    # log_progress_interval: 10

  save_planner_log: true