# configs/modules/progress_tracking.yaml

# Project root directory
project_root: "."

# ===============================
# PROGRESS TRACKING MODULE CONFIG
# ===============================
progress_tracking:
# REQUIRED_FIELDS = {
# 'annotation_path': str, 
# 'databaseSchemas_path': str, 
# 'validation_change_log_path': str, 
# 'progress_tracker_dir': str}

  # Source data directory (dynamic database)
  db_dir: "tests/mock_database" 
  # => databaseSchemas_path = f"{self.db_dir}/databaseSchemas.json"

  default_dir: 'tests/shared_db'
  #annotation_path = f"{default_dir}/DataPipelineOrchestrator/DataLoaderAgent/newest/path_annotations.json" 
  #validation_change_log_path = f"{self.default_dir}/ValidationOrchestrator/change_log.txt"
  #progress_tracker_dir = f"{self.default_dir}/OrderProgressTracker"