# configs/modules/progress_tracking.yaml

# Project root directory
project_root: "."

# ===============================
# PROGRESS TRACKING MODULE CONFIG
# ===============================
progress_tracking:

  # Main shared database from DataPipeline
  source_path: 'tests/shared_db/DataLoaderAgent/newest' # Directory
  annotation_name: "path_annotations.json"              # Annotation name

  # Database schema definitions
  databaseSchemas_path: "tests/mock_database/databaseSchemas.json"

  # Change log from ValidationOrchestrator
  folder_path: "tests/shared_db/ValidationOrchestrator"
  target_name: "change_log.txt"

  # Default output directory for processed data
  default_dir: "tests/shared_db"

  # Report formatting
  use_colored_report: true